#include <Arduino.h>
#include <cmath>
#include <ESP32Servo.h>
#include "AstraMisc.h"
#include "AstraVicCAN.h"

// Remove to disable the boards inbuilt LED blinking
#define BLINK
#define CAN_TX		5
#define CAN_RX		4

bool ledState = false;
// Servo Pins (generated by Gemini): 13,14,18,19,22,23,25,26,27


// Defined servos (3 for valves, 3 for distributors, 3 for chemicals)
Servo valve1, valve2, valve3, distributor1, distributor2, distributor3, chemical1, chemical2, chemical3;

long lastWiggle = 0;  // For PWM servos
bool servoStates[9] = {false, false, false, false, false, false, false, false, false};
int servoPositions[9] = {0, 0, 0 ,0 ,0 ,0 ,0, 0, 0};

void setup() {
  // put your setup code here, to run once:
  Serial.begin(115200); // May need to change this later



    // Valves are on top of the unit
  valve1.attach(13);
  valve2.attach(14);
  valve3.attach(18);

  // Distributors are on each of the pieces that hang down
  distributor1.attach(19);
  distributor2.attach(22);
  distributor3.attach(23);

  // Chemical servos are in the back of the unit (the larger servos)
  chemical1.attach(25);
  chemical2.attach(26);
  chemical3.attach(27);

  Serial.begin(SERIAL_BAUD);

  ESP32Can.begin(TWAI_SPEED_1000KBPS, CAN_TX, CAN_RX);
}

void loop() {
  // put your main code here, to run repeatedly:

  if (millis() - lastWiggle > 1000) {
    lastWiggle = millis();
    if (servoStates[0]) {
        servoPositions[0] = (servoPositions[0] == 0 ? 180 : 0);
        valve1.write(servoPositions[0]);
    }
    if (servoStates[1]) {
        servoPositions[1] = (servoPositions[1] == 0 ? 180 : 0);
        valve2.write(servoPositions[1]);
    }
    if (servoStates[2]) {
        servoPositions[2] = (servoPositions[2] == 0 ? 180 : 0);
        valve3.write(servoPositions[2]);
    }
    if (servoStates[3]) {
      servoPositions[3] = (servoPositions[3] == 0 ? 180 : 0);
      distributor1.write(servoPositions[3]);
    }
    if (servoStates[4]) {
      servoPositions[4] = (servoPositions[4] == 0 ? 180 : 0);
      distributor2.write(servoPositions[4]);
    }
    if (servoStates[5]) {
      servoPositions[5] = (servoPositions[5] == 0 ? 180 : 0);
      distributor3.write(servoPositions[5]);
    }
    if (servoStates[6]) {
      servoPositions[6] = (servoPositions[6] == 0 ? 180 : 0);
      chemical1.write(servoPositions[6]);
    }
    if (servoStates[7]) {
      servoPositions[7] = (servoPositions[7] == 0 ? 180 : 0);
      chemical2.write(servoPositions[7]);
    }
    if (servoStates[8]) {
      servoPositions[8] = (servoPositions[8] == 0 ? 180 : 0);
      chemical3.write(servoPositions[8]);
    }


    // Serial commands
    if (Serial.available())
    {
        String input = Serial.readStringUntil('\n');
        Serial.println(input);

        input.trim();                    // Remove preceding and trailing whitespace
        std::vector<String> args = {}; // Initialize empty vector to hold separated arguments
        parseInput(input, args); // Separate `input` by commas and place into args vector
        args[0].toLowerCase();         // Make command case-insensitive
        String command = args[0];      // To make processing code more readable

        //--------//
        //  Misc  //
        //--------//
        /**/ if (command == "ping")
        {
            Serial.println("pong");
        }

        else if (command == "time")
        {
            Serial.println(millis());
        }

        else if (command == "led") // This command will not work when using boards that do not have a inbuilt LED (i.e. the Dev Module 1)
        {
            digitalWrite(LED_BUILTIN, !ledState);
            ledState = !ledState;
        }

        else if (args[0] == "can_relay_tovic")
        {
            vicCAN.relayFromSerial(args);
        }

        else if (args[0] == "can_relay_mode")
        {
            if (args[1] == "on")
            {
                vicCAN.relayOn();
            }
            else if (args[1] == "off")
            {
                vicCAN.relayOff();
            }
        }
        else if (args[0] == "servo")
        {
            switch (args[1].toInt())
            {
            case 1:
                valve1.write(args[2].toInt());
                break;
            case 2:
                valve2.write(args[2].toInt());
                break;
            case 3:
                valve3.write(args[2].toInt());
                break;
            case 4:
              distributor1.write(args[2].toInt());
              break;
            case 5:
              distributor2.write(args[2].toInt());
              break;
            case 6:
              distributor3.write(args[2].toInt());
              break;
            case 7:
              chemical1.write(args[2].toInt());
              break;
            case 8:
              chemical2.write(args[2].toInt());
              break;
            case 9: 
              chemical3.write(args[2].toInt());
              break;
            default:
                break;
            }
        }
        else if (args[0] == "shutdown")
        {
          // TODO: Add pins here
          valve1.detach();
          valve2.detach();
          valve3.detach();

          distributor1.detach();
          distributor2.detach();
          distributor3.detach();

          chemical1.detach();
          chemical2.detach();
          chemical3.detach();
        }
    }

      
    if (vicCAN.readCan())
    {
        const uint8_t commandID = vicCAN.getCmdId();
        static std::vector<double> canData;
        vicCAN.parseData(canData);

        Serial.print("VicCAN: ");
        Serial.print(commandID);
        Serial.print("; ");
        if (canData.size() > 0)
        {
            for (const double &data : canData)
            {
                Serial.print(data);
                Serial.print(", ");
            }
        }
        Serial.println();


        // Misc

        if (commandID == CMD_PING)
        {
            vicCAN.respond(1); // "pong"
            Serial.println("Received ping over CAN");
        }
    }

}
}

